apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Monitoring resources should not have namespace applied by kustomize
# as they need to be in the 'monitoring' namespace, not 'flowagent'

resources:
- namespace.yaml
- prometheus.yaml
