apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Monitoring stack resources
# This is kept separate because it uses the 'monitoring' namespace

resources:
- ../../../apps/monitoring

labels:
- pairs:
    environment: production
    component: monitoring
